// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	base "github.com/anhao26/zero-cloud/service/system/api/internal/handler/base"
	captcha "github.com/anhao26/zero-cloud/service/system/api/internal/handler/captcha"
	"github.com/anhao26/zero-cloud/service/system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: captcha.GetCaptchaHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/init/database",
				Handler: base.InitDatabaseHandler(serverCtx),
			},
		},
	)
}
