// Code generated by ent, DO NOT EDIT.

package attributeoption

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/anhao26/zero-cloud/service/ticket/ticket-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldUpdatedAt, v))
}

// AttributeID applies equality check predicate on the "attribute_id" field. It's identical to AttributeIDEQ.
func AttributeID(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldAttributeID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldValue, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLTE(FieldUpdatedAt, v))
}

// AttributeIDEQ applies the EQ predicate on the "attribute_id" field.
func AttributeIDEQ(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldAttributeID, v))
}

// AttributeIDNEQ applies the NEQ predicate on the "attribute_id" field.
func AttributeIDNEQ(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNEQ(FieldAttributeID, v))
}

// AttributeIDIn applies the In predicate on the "attribute_id" field.
func AttributeIDIn(vs ...uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldIn(FieldAttributeID, vs...))
}

// AttributeIDNotIn applies the NotIn predicate on the "attribute_id" field.
func AttributeIDNotIn(vs ...uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNotIn(FieldAttributeID, vs...))
}

// AttributeIDGT applies the GT predicate on the "attribute_id" field.
func AttributeIDGT(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGT(FieldAttributeID, v))
}

// AttributeIDGTE applies the GTE predicate on the "attribute_id" field.
func AttributeIDGTE(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGTE(FieldAttributeID, v))
}

// AttributeIDLT applies the LT predicate on the "attribute_id" field.
func AttributeIDLT(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLT(FieldAttributeID, v))
}

// AttributeIDLTE applies the LTE predicate on the "attribute_id" field.
func AttributeIDLTE(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLTE(FieldAttributeID, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldContainsFold(FieldLabel, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v uint64) predicate.AttributeOption {
	return predicate.AttributeOption(sql.FieldLTE(FieldValue, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AttributeOption) predicate.AttributeOption {
	return predicate.AttributeOption(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AttributeOption) predicate.AttributeOption {
	return predicate.AttributeOption(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AttributeOption) predicate.AttributeOption {
	return predicate.AttributeOption(func(s *sql.Selector) {
		p(s.Not())
	})
}
