// Code generated by ent, DO NOT EDIT.

package attributegroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/anhao26/zero-cloud/service/ticket/ticket-rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// AttributeSetID applies equality check predicate on the "attribute_set_id" field. It's identical to AttributeSetIDEQ.
func AttributeSetID(v uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldAttributeSetID, v))
}

// AttributeGroupName applies equality check predicate on the "attribute_group_name" field. It's identical to AttributeGroupNameEQ.
func AttributeGroupName(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldAttributeGroupName, v))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldSequence, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// AttributeSetIDEQ applies the EQ predicate on the "attribute_set_id" field.
func AttributeSetIDEQ(v uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldAttributeSetID, v))
}

// AttributeSetIDNEQ applies the NEQ predicate on the "attribute_set_id" field.
func AttributeSetIDNEQ(v uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNEQ(FieldAttributeSetID, v))
}

// AttributeSetIDIn applies the In predicate on the "attribute_set_id" field.
func AttributeSetIDIn(vs ...uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldIn(FieldAttributeSetID, vs...))
}

// AttributeSetIDNotIn applies the NotIn predicate on the "attribute_set_id" field.
func AttributeSetIDNotIn(vs ...uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNotIn(FieldAttributeSetID, vs...))
}

// AttributeSetIDGT applies the GT predicate on the "attribute_set_id" field.
func AttributeSetIDGT(v uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGT(FieldAttributeSetID, v))
}

// AttributeSetIDGTE applies the GTE predicate on the "attribute_set_id" field.
func AttributeSetIDGTE(v uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGTE(FieldAttributeSetID, v))
}

// AttributeSetIDLT applies the LT predicate on the "attribute_set_id" field.
func AttributeSetIDLT(v uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLT(FieldAttributeSetID, v))
}

// AttributeSetIDLTE applies the LTE predicate on the "attribute_set_id" field.
func AttributeSetIDLTE(v uint64) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLTE(FieldAttributeSetID, v))
}

// AttributeGroupNameEQ applies the EQ predicate on the "attribute_group_name" field.
func AttributeGroupNameEQ(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldAttributeGroupName, v))
}

// AttributeGroupNameNEQ applies the NEQ predicate on the "attribute_group_name" field.
func AttributeGroupNameNEQ(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNEQ(FieldAttributeGroupName, v))
}

// AttributeGroupNameIn applies the In predicate on the "attribute_group_name" field.
func AttributeGroupNameIn(vs ...string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldIn(FieldAttributeGroupName, vs...))
}

// AttributeGroupNameNotIn applies the NotIn predicate on the "attribute_group_name" field.
func AttributeGroupNameNotIn(vs ...string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNotIn(FieldAttributeGroupName, vs...))
}

// AttributeGroupNameGT applies the GT predicate on the "attribute_group_name" field.
func AttributeGroupNameGT(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGT(FieldAttributeGroupName, v))
}

// AttributeGroupNameGTE applies the GTE predicate on the "attribute_group_name" field.
func AttributeGroupNameGTE(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGTE(FieldAttributeGroupName, v))
}

// AttributeGroupNameLT applies the LT predicate on the "attribute_group_name" field.
func AttributeGroupNameLT(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLT(FieldAttributeGroupName, v))
}

// AttributeGroupNameLTE applies the LTE predicate on the "attribute_group_name" field.
func AttributeGroupNameLTE(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLTE(FieldAttributeGroupName, v))
}

// AttributeGroupNameContains applies the Contains predicate on the "attribute_group_name" field.
func AttributeGroupNameContains(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldContains(FieldAttributeGroupName, v))
}

// AttributeGroupNameHasPrefix applies the HasPrefix predicate on the "attribute_group_name" field.
func AttributeGroupNameHasPrefix(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldHasPrefix(FieldAttributeGroupName, v))
}

// AttributeGroupNameHasSuffix applies the HasSuffix predicate on the "attribute_group_name" field.
func AttributeGroupNameHasSuffix(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldHasSuffix(FieldAttributeGroupName, v))
}

// AttributeGroupNameEqualFold applies the EqualFold predicate on the "attribute_group_name" field.
func AttributeGroupNameEqualFold(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEqualFold(FieldAttributeGroupName, v))
}

// AttributeGroupNameContainsFold applies the ContainsFold predicate on the "attribute_group_name" field.
func AttributeGroupNameContainsFold(v string) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldContainsFold(FieldAttributeGroupName, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v uint8) predicate.AttributeGroup {
	return predicate.AttributeGroup(sql.FieldLTE(FieldSequence, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AttributeGroup) predicate.AttributeGroup {
	return predicate.AttributeGroup(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AttributeGroup) predicate.AttributeGroup {
	return predicate.AttributeGroup(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AttributeGroup) predicate.AttributeGroup {
	return predicate.AttributeGroup(func(s *sql.Selector) {
		p(s.Not())
	})
}
