// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anhao26/zero-cloud/service/system/rpc/ent/rpc"
)

// Rpc is the model entity for the Rpc schema.
type Rpc struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Rpc) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rpc.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Rpc fields.
func (r *Rpc) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rpc.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Rpc.
// This includes values selected through modifiers, order, etc.
func (r *Rpc) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// Update returns a builder for updating this Rpc.
// Note that you need to call Rpc.Unwrap() before calling this method if this Rpc
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Rpc) Update() *RPCUpdateOne {
	return NewRPCClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Rpc entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Rpc) Unwrap() *Rpc {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Rpc is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Rpc) String() string {
	var builder strings.Builder
	builder.WriteString("Rpc(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Rpcs is a parsable slice of Rpc.
type Rpcs []*Rpc
