// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anhao26/zero-cloud/service/ticket/ticket-rpc/ent/attributeoption"
)

// AttributeOptionCreate is the builder for creating a AttributeOption entity.
type AttributeOptionCreate struct {
	config
	mutation *AttributeOptionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (aoc *AttributeOptionCreate) SetCreatedAt(t time.Time) *AttributeOptionCreate {
	aoc.mutation.SetCreatedAt(t)
	return aoc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aoc *AttributeOptionCreate) SetNillableCreatedAt(t *time.Time) *AttributeOptionCreate {
	if t != nil {
		aoc.SetCreatedAt(*t)
	}
	return aoc
}

// SetUpdatedAt sets the "updated_at" field.
func (aoc *AttributeOptionCreate) SetUpdatedAt(t time.Time) *AttributeOptionCreate {
	aoc.mutation.SetUpdatedAt(t)
	return aoc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (aoc *AttributeOptionCreate) SetNillableUpdatedAt(t *time.Time) *AttributeOptionCreate {
	if t != nil {
		aoc.SetUpdatedAt(*t)
	}
	return aoc
}

// SetAttributeID sets the "attribute_id" field.
func (aoc *AttributeOptionCreate) SetAttributeID(u uint64) *AttributeOptionCreate {
	aoc.mutation.SetAttributeID(u)
	return aoc
}

// SetLabel sets the "label" field.
func (aoc *AttributeOptionCreate) SetLabel(s string) *AttributeOptionCreate {
	aoc.mutation.SetLabel(s)
	return aoc
}

// SetValue sets the "value" field.
func (aoc *AttributeOptionCreate) SetValue(u uint64) *AttributeOptionCreate {
	aoc.mutation.SetValue(u)
	return aoc
}

// SetID sets the "id" field.
func (aoc *AttributeOptionCreate) SetID(u uint64) *AttributeOptionCreate {
	aoc.mutation.SetID(u)
	return aoc
}

// Mutation returns the AttributeOptionMutation object of the builder.
func (aoc *AttributeOptionCreate) Mutation() *AttributeOptionMutation {
	return aoc.mutation
}

// Save creates the AttributeOption in the database.
func (aoc *AttributeOptionCreate) Save(ctx context.Context) (*AttributeOption, error) {
	aoc.defaults()
	return withHooks(ctx, aoc.sqlSave, aoc.mutation, aoc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (aoc *AttributeOptionCreate) SaveX(ctx context.Context) *AttributeOption {
	v, err := aoc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aoc *AttributeOptionCreate) Exec(ctx context.Context) error {
	_, err := aoc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aoc *AttributeOptionCreate) ExecX(ctx context.Context) {
	if err := aoc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aoc *AttributeOptionCreate) defaults() {
	if _, ok := aoc.mutation.CreatedAt(); !ok {
		v := attributeoption.DefaultCreatedAt()
		aoc.mutation.SetCreatedAt(v)
	}
	if _, ok := aoc.mutation.UpdatedAt(); !ok {
		v := attributeoption.DefaultUpdatedAt()
		aoc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aoc *AttributeOptionCreate) check() error {
	if _, ok := aoc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AttributeOption.created_at"`)}
	}
	if _, ok := aoc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AttributeOption.updated_at"`)}
	}
	if _, ok := aoc.mutation.AttributeID(); !ok {
		return &ValidationError{Name: "attribute_id", err: errors.New(`ent: missing required field "AttributeOption.attribute_id"`)}
	}
	if _, ok := aoc.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "AttributeOption.label"`)}
	}
	if _, ok := aoc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "AttributeOption.value"`)}
	}
	return nil
}

func (aoc *AttributeOptionCreate) sqlSave(ctx context.Context) (*AttributeOption, error) {
	if err := aoc.check(); err != nil {
		return nil, err
	}
	_node, _spec := aoc.createSpec()
	if err := sqlgraph.CreateNode(ctx, aoc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	aoc.mutation.id = &_node.ID
	aoc.mutation.done = true
	return _node, nil
}

func (aoc *AttributeOptionCreate) createSpec() (*AttributeOption, *sqlgraph.CreateSpec) {
	var (
		_node = &AttributeOption{config: aoc.config}
		_spec = sqlgraph.NewCreateSpec(attributeoption.Table, sqlgraph.NewFieldSpec(attributeoption.FieldID, field.TypeUint64))
	)
	if id, ok := aoc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := aoc.mutation.CreatedAt(); ok {
		_spec.SetField(attributeoption.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := aoc.mutation.UpdatedAt(); ok {
		_spec.SetField(attributeoption.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := aoc.mutation.AttributeID(); ok {
		_spec.SetField(attributeoption.FieldAttributeID, field.TypeUint64, value)
		_node.AttributeID = value
	}
	if value, ok := aoc.mutation.Label(); ok {
		_spec.SetField(attributeoption.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := aoc.mutation.Value(); ok {
		_spec.SetField(attributeoption.FieldValue, field.TypeUint64, value)
		_node.Value = value
	}
	return _node, _spec
}

// AttributeOptionCreateBulk is the builder for creating many AttributeOption entities in bulk.
type AttributeOptionCreateBulk struct {
	config
	builders []*AttributeOptionCreate
}

// Save creates the AttributeOption entities in the database.
func (aocb *AttributeOptionCreateBulk) Save(ctx context.Context) ([]*AttributeOption, error) {
	specs := make([]*sqlgraph.CreateSpec, len(aocb.builders))
	nodes := make([]*AttributeOption, len(aocb.builders))
	mutators := make([]Mutator, len(aocb.builders))
	for i := range aocb.builders {
		func(i int, root context.Context) {
			builder := aocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttributeOptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aocb *AttributeOptionCreateBulk) SaveX(ctx context.Context) []*AttributeOption {
	v, err := aocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aocb *AttributeOptionCreateBulk) Exec(ctx context.Context) error {
	_, err := aocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aocb *AttributeOptionCreateBulk) ExecX(ctx context.Context) {
	if err := aocb.Exec(ctx); err != nil {
		panic(err)
	}
}
