// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anhao26/zero-cloud/service/ticket/ticket-rpc/ent/attribute"
	"github.com/anhao26/zero-cloud/service/ticket/ticket-rpc/ent/attributeoption"
	"github.com/anhao26/zero-cloud/service/ticket/ticket-rpc/ent/entity"
)

// AttributeCreate is the builder for creating a Attribute entity.
type AttributeCreate struct {
	config
	mutation *AttributeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ac *AttributeCreate) SetCreatedAt(t time.Time) *AttributeCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AttributeCreate) SetNillableCreatedAt(t *time.Time) *AttributeCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AttributeCreate) SetUpdatedAt(t time.Time) *AttributeCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AttributeCreate) SetNillableUpdatedAt(t *time.Time) *AttributeCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetEntityID sets the "entity_id" field.
func (ac *AttributeCreate) SetEntityID(u uint64) *AttributeCreate {
	ac.mutation.SetEntityID(u)
	return ac
}

// SetAttributeCode sets the "attribute_code" field.
func (ac *AttributeCreate) SetAttributeCode(s string) *AttributeCreate {
	ac.mutation.SetAttributeCode(s)
	return ac
}

// SetBackendClass sets the "backend_class" field.
func (ac *AttributeCreate) SetBackendClass(s string) *AttributeCreate {
	ac.mutation.SetBackendClass(s)
	return ac
}

// SetBackendType sets the "backend_type" field.
func (ac *AttributeCreate) SetBackendType(s string) *AttributeCreate {
	ac.mutation.SetBackendType(s)
	return ac
}

// SetBackendTable sets the "backend_table" field.
func (ac *AttributeCreate) SetBackendTable(s string) *AttributeCreate {
	ac.mutation.SetBackendTable(s)
	return ac
}

// SetFrontendClass sets the "frontend_class" field.
func (ac *AttributeCreate) SetFrontendClass(s string) *AttributeCreate {
	ac.mutation.SetFrontendClass(s)
	return ac
}

// SetFrontendType sets the "frontend_type" field.
func (ac *AttributeCreate) SetFrontendType(s string) *AttributeCreate {
	ac.mutation.SetFrontendType(s)
	return ac
}

// SetFrontendLabel sets the "frontend_label" field.
func (ac *AttributeCreate) SetFrontendLabel(s string) *AttributeCreate {
	ac.mutation.SetFrontendLabel(s)
	return ac
}

// SetSourceClass sets the "source_class" field.
func (ac *AttributeCreate) SetSourceClass(s string) *AttributeCreate {
	ac.mutation.SetSourceClass(s)
	return ac
}

// SetDefaultValue sets the "default_value" field.
func (ac *AttributeCreate) SetDefaultValue(s string) *AttributeCreate {
	ac.mutation.SetDefaultValue(s)
	return ac
}

// SetIsFilterable sets the "is_filterable" field.
func (ac *AttributeCreate) SetIsFilterable(u uint8) *AttributeCreate {
	ac.mutation.SetIsFilterable(u)
	return ac
}

// SetNillableIsFilterable sets the "is_filterable" field if the given value is not nil.
func (ac *AttributeCreate) SetNillableIsFilterable(u *uint8) *AttributeCreate {
	if u != nil {
		ac.SetIsFilterable(*u)
	}
	return ac
}

// SetIsSearchable sets the "is_searchable" field.
func (ac *AttributeCreate) SetIsSearchable(u uint8) *AttributeCreate {
	ac.mutation.SetIsSearchable(u)
	return ac
}

// SetNillableIsSearchable sets the "is_searchable" field if the given value is not nil.
func (ac *AttributeCreate) SetNillableIsSearchable(u *uint8) *AttributeCreate {
	if u != nil {
		ac.SetIsSearchable(*u)
	}
	return ac
}

// SetIsRequired sets the "is_required" field.
func (ac *AttributeCreate) SetIsRequired(u uint8) *AttributeCreate {
	ac.mutation.SetIsRequired(u)
	return ac
}

// SetNillableIsRequired sets the "is_required" field if the given value is not nil.
func (ac *AttributeCreate) SetNillableIsRequired(u *uint8) *AttributeCreate {
	if u != nil {
		ac.SetIsRequired(*u)
	}
	return ac
}

// SetRequiredValidateClass sets the "required_validate_class" field.
func (ac *AttributeCreate) SetRequiredValidateClass(s string) *AttributeCreate {
	ac.mutation.SetRequiredValidateClass(s)
	return ac
}

// SetID sets the "id" field.
func (ac *AttributeCreate) SetID(u uint64) *AttributeCreate {
	ac.mutation.SetID(u)
	return ac
}

// AddEntityIDs adds the "entities" edge to the Entity entity by IDs.
func (ac *AttributeCreate) AddEntityIDs(ids ...uint64) *AttributeCreate {
	ac.mutation.AddEntityIDs(ids...)
	return ac
}

// AddEntities adds the "entities" edges to the Entity entity.
func (ac *AttributeCreate) AddEntities(e ...*Entity) *AttributeCreate {
	ids := make([]uint64, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return ac.AddEntityIDs(ids...)
}

// AddAttributeOptionIDs adds the "attribute_options" edge to the AttributeOption entity by IDs.
func (ac *AttributeCreate) AddAttributeOptionIDs(ids ...uint64) *AttributeCreate {
	ac.mutation.AddAttributeOptionIDs(ids...)
	return ac
}

// AddAttributeOptions adds the "attribute_options" edges to the AttributeOption entity.
func (ac *AttributeCreate) AddAttributeOptions(a ...*AttributeOption) *AttributeCreate {
	ids := make([]uint64, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ac.AddAttributeOptionIDs(ids...)
}

// Mutation returns the AttributeMutation object of the builder.
func (ac *AttributeCreate) Mutation() *AttributeMutation {
	return ac.mutation
}

// Save creates the Attribute in the database.
func (ac *AttributeCreate) Save(ctx context.Context) (*Attribute, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AttributeCreate) SaveX(ctx context.Context) *Attribute {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AttributeCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AttributeCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AttributeCreate) defaults() {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := attribute.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		v := attribute.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
	if _, ok := ac.mutation.IsFilterable(); !ok {
		v := attribute.DefaultIsFilterable
		ac.mutation.SetIsFilterable(v)
	}
	if _, ok := ac.mutation.IsSearchable(); !ok {
		v := attribute.DefaultIsSearchable
		ac.mutation.SetIsSearchable(v)
	}
	if _, ok := ac.mutation.IsRequired(); !ok {
		v := attribute.DefaultIsRequired
		ac.mutation.SetIsRequired(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AttributeCreate) check() error {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Attribute.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Attribute.updated_at"`)}
	}
	if _, ok := ac.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "Attribute.entity_id"`)}
	}
	if _, ok := ac.mutation.AttributeCode(); !ok {
		return &ValidationError{Name: "attribute_code", err: errors.New(`ent: missing required field "Attribute.attribute_code"`)}
	}
	if _, ok := ac.mutation.BackendClass(); !ok {
		return &ValidationError{Name: "backend_class", err: errors.New(`ent: missing required field "Attribute.backend_class"`)}
	}
	if _, ok := ac.mutation.BackendType(); !ok {
		return &ValidationError{Name: "backend_type", err: errors.New(`ent: missing required field "Attribute.backend_type"`)}
	}
	if _, ok := ac.mutation.BackendTable(); !ok {
		return &ValidationError{Name: "backend_table", err: errors.New(`ent: missing required field "Attribute.backend_table"`)}
	}
	if _, ok := ac.mutation.FrontendClass(); !ok {
		return &ValidationError{Name: "frontend_class", err: errors.New(`ent: missing required field "Attribute.frontend_class"`)}
	}
	if _, ok := ac.mutation.FrontendType(); !ok {
		return &ValidationError{Name: "frontend_type", err: errors.New(`ent: missing required field "Attribute.frontend_type"`)}
	}
	if _, ok := ac.mutation.FrontendLabel(); !ok {
		return &ValidationError{Name: "frontend_label", err: errors.New(`ent: missing required field "Attribute.frontend_label"`)}
	}
	if _, ok := ac.mutation.SourceClass(); !ok {
		return &ValidationError{Name: "source_class", err: errors.New(`ent: missing required field "Attribute.source_class"`)}
	}
	if _, ok := ac.mutation.DefaultValue(); !ok {
		return &ValidationError{Name: "default_value", err: errors.New(`ent: missing required field "Attribute.default_value"`)}
	}
	if _, ok := ac.mutation.IsFilterable(); !ok {
		return &ValidationError{Name: "is_filterable", err: errors.New(`ent: missing required field "Attribute.is_filterable"`)}
	}
	if _, ok := ac.mutation.IsSearchable(); !ok {
		return &ValidationError{Name: "is_searchable", err: errors.New(`ent: missing required field "Attribute.is_searchable"`)}
	}
	if _, ok := ac.mutation.IsRequired(); !ok {
		return &ValidationError{Name: "is_required", err: errors.New(`ent: missing required field "Attribute.is_required"`)}
	}
	if _, ok := ac.mutation.RequiredValidateClass(); !ok {
		return &ValidationError{Name: "required_validate_class", err: errors.New(`ent: missing required field "Attribute.required_validate_class"`)}
	}
	return nil
}

func (ac *AttributeCreate) sqlSave(ctx context.Context) (*Attribute, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AttributeCreate) createSpec() (*Attribute, *sqlgraph.CreateSpec) {
	var (
		_node = &Attribute{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(attribute.Table, sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeUint64))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(attribute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(attribute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ac.mutation.EntityID(); ok {
		_spec.SetField(attribute.FieldEntityID, field.TypeUint64, value)
		_node.EntityID = value
	}
	if value, ok := ac.mutation.AttributeCode(); ok {
		_spec.SetField(attribute.FieldAttributeCode, field.TypeString, value)
		_node.AttributeCode = value
	}
	if value, ok := ac.mutation.BackendClass(); ok {
		_spec.SetField(attribute.FieldBackendClass, field.TypeString, value)
		_node.BackendClass = value
	}
	if value, ok := ac.mutation.BackendType(); ok {
		_spec.SetField(attribute.FieldBackendType, field.TypeString, value)
		_node.BackendType = value
	}
	if value, ok := ac.mutation.BackendTable(); ok {
		_spec.SetField(attribute.FieldBackendTable, field.TypeString, value)
		_node.BackendTable = value
	}
	if value, ok := ac.mutation.FrontendClass(); ok {
		_spec.SetField(attribute.FieldFrontendClass, field.TypeString, value)
		_node.FrontendClass = value
	}
	if value, ok := ac.mutation.FrontendType(); ok {
		_spec.SetField(attribute.FieldFrontendType, field.TypeString, value)
		_node.FrontendType = value
	}
	if value, ok := ac.mutation.FrontendLabel(); ok {
		_spec.SetField(attribute.FieldFrontendLabel, field.TypeString, value)
		_node.FrontendLabel = value
	}
	if value, ok := ac.mutation.SourceClass(); ok {
		_spec.SetField(attribute.FieldSourceClass, field.TypeString, value)
		_node.SourceClass = value
	}
	if value, ok := ac.mutation.DefaultValue(); ok {
		_spec.SetField(attribute.FieldDefaultValue, field.TypeString, value)
		_node.DefaultValue = value
	}
	if value, ok := ac.mutation.IsFilterable(); ok {
		_spec.SetField(attribute.FieldIsFilterable, field.TypeUint8, value)
		_node.IsFilterable = value
	}
	if value, ok := ac.mutation.IsSearchable(); ok {
		_spec.SetField(attribute.FieldIsSearchable, field.TypeUint8, value)
		_node.IsSearchable = value
	}
	if value, ok := ac.mutation.IsRequired(); ok {
		_spec.SetField(attribute.FieldIsRequired, field.TypeUint8, value)
		_node.IsRequired = value
	}
	if value, ok := ac.mutation.RequiredValidateClass(); ok {
		_spec.SetField(attribute.FieldRequiredValidateClass, field.TypeString, value)
		_node.RequiredValidateClass = value
	}
	if nodes := ac.mutation.EntitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.EntitiesTable,
			Columns: []string{attribute.EntitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.AttributeOptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.AttributeOptionsTable,
			Columns: []string{attribute.AttributeOptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attributeoption.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttributeCreateBulk is the builder for creating many Attribute entities in bulk.
type AttributeCreateBulk struct {
	config
	builders []*AttributeCreate
}

// Save creates the Attribute entities in the database.
func (acb *AttributeCreateBulk) Save(ctx context.Context) ([]*Attribute, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Attribute, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttributeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AttributeCreateBulk) SaveX(ctx context.Context) []*Attribute {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AttributeCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AttributeCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
