// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anhao26/zero-cloud/service/ticket/ticket-rpc/ent/entity"
)

// Entity is the model entity for the Entity schema.
type Entity struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Entity Code | 实体标识
	EntityCode string `json:"entity_code,omitempty"`
	// Entity Class | 实体类
	EntityClass string `json:"entity_class,omitempty"`
	// Entity Table | 实体表名称
	EntityTable string `json:"entity_table,omitempty"`
	// Default Attribute Set Id | 默认属性SET ID
	DefaultAttributeSetID uint64 `json:"default_attribute_set_id,omitempty"`
	// Additional Attribute Table | 附加属性表
	AdditionalAttributeTable string `json:"additional_attribute_table,omitempty"`
	// Is Flat Enabled | 是否设置一张表存储
	IsFlatEnabled uint32 `json:"is_flat_enabled,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Entity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entity.FieldID, entity.FieldDefaultAttributeSetID, entity.FieldIsFlatEnabled:
			values[i] = new(sql.NullInt64)
		case entity.FieldEntityCode, entity.FieldEntityClass, entity.FieldEntityTable, entity.FieldAdditionalAttributeTable:
			values[i] = new(sql.NullString)
		case entity.FieldCreatedAt, entity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Entity fields.
func (e *Entity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			e.ID = uint64(value.Int64)
		case entity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				e.CreatedAt = value.Time
			}
		case entity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				e.UpdatedAt = value.Time
			}
		case entity.FieldEntityCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_code", values[i])
			} else if value.Valid {
				e.EntityCode = value.String
			}
		case entity.FieldEntityClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_class", values[i])
			} else if value.Valid {
				e.EntityClass = value.String
			}
		case entity.FieldEntityTable:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_table", values[i])
			} else if value.Valid {
				e.EntityTable = value.String
			}
		case entity.FieldDefaultAttributeSetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_attribute_set_id", values[i])
			} else if value.Valid {
				e.DefaultAttributeSetID = uint64(value.Int64)
			}
		case entity.FieldAdditionalAttributeTable:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field additional_attribute_table", values[i])
			} else if value.Valid {
				e.AdditionalAttributeTable = value.String
			}
		case entity.FieldIsFlatEnabled:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_flat_enabled", values[i])
			} else if value.Valid {
				e.IsFlatEnabled = uint32(value.Int64)
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Entity.
// This includes values selected through modifiers, order, etc.
func (e *Entity) Value(name string) (ent.Value, error) {
	return e.selectValues.Get(name)
}

// Update returns a builder for updating this Entity.
// Note that you need to call Entity.Unwrap() before calling this method if this Entity
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Entity) Update() *EntityUpdateOne {
	return NewEntityClient(e.config).UpdateOne(e)
}

// Unwrap unwraps the Entity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Entity) Unwrap() *Entity {
	_tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Entity is not a transactional entity")
	}
	e.config.driver = _tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Entity) String() string {
	var builder strings.Builder
	builder.WriteString("Entity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", e.ID))
	builder.WriteString("created_at=")
	builder.WriteString(e.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(e.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entity_code=")
	builder.WriteString(e.EntityCode)
	builder.WriteString(", ")
	builder.WriteString("entity_class=")
	builder.WriteString(e.EntityClass)
	builder.WriteString(", ")
	builder.WriteString("entity_table=")
	builder.WriteString(e.EntityTable)
	builder.WriteString(", ")
	builder.WriteString("default_attribute_set_id=")
	builder.WriteString(fmt.Sprintf("%v", e.DefaultAttributeSetID))
	builder.WriteString(", ")
	builder.WriteString("additional_attribute_table=")
	builder.WriteString(e.AdditionalAttributeTable)
	builder.WriteString(", ")
	builder.WriteString("is_flat_enabled=")
	builder.WriteString(fmt.Sprintf("%v", e.IsFlatEnabled))
	builder.WriteByte(')')
	return builder.String()
}

// Entities is a parsable slice of Entity.
type Entities []*Entity
