// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/anhao26/zero-cloud/service/ticket/ticket-rpc/ent/entity"
)

const errInvalidPage = "INVALID_PAGE"

const (
	listField     = "list"
	pageNumField  = "pageNum"
	pageSizeField = "pageSize"
)

type PageDetails struct {
	Page  uint64 `json:"page"`
	Size  uint64 `json:"size"`
	Total uint64 `json:"total"`
}

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

const errInvalidPagination = "INVALID_PAGINATION"

type EntityPager struct {
	Order  entity.OrderOption
	Filter func(*EntityQuery) (*EntityQuery, error)
}

// EntityPaginateOption enables pagination customization.
type EntityPaginateOption func(*EntityPager)

// DefaultEntityOrder is the default ordering of Entity.
var DefaultEntityOrder = Desc(entity.FieldID)

func newEntityPager(opts []EntityPaginateOption) (*EntityPager, error) {
	pager := &EntityPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultEntityOrder
	}
	return pager, nil
}

func (p *EntityPager) ApplyFilter(query *EntityQuery) (*EntityQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// EntityPageList is Entity PageList result.
type EntityPageList struct {
	List        []*Entity    `json:"list"`
	PageDetails *PageDetails `json:"pageDetails"`
}

func (e *EntityQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...EntityPaginateOption,
) (*EntityPageList, error) {

	pager, err := newEntityPager(opts)
	if err != nil {
		return nil, err
	}

	if e, err = pager.ApplyFilter(e); err != nil {
		return nil, err
	}

	ret := &EntityPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	count, err := e.Clone().Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		e = e.Order(pager.Order)
	} else {
		e = e.Order(DefaultEntityOrder)
	}

	e = e.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := e.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}
