// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RpcsColumns holds the columns for the "rpcs" table.
	RpcsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// RpcsTable holds the schema information for the "rpcs" table.
	RpcsTable = &schema.Table{
		Name:       "rpcs",
		Columns:    RpcsColumns,
		PrimaryKey: []*schema.Column{RpcsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RpcsTable,
	}
)

func init() {
}
